name: bench
on: [push]
jobs:
  run-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
      - name: Run benchmarks
        run: |
          python bench/run_all.py
          python viz/plot_results.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            results.csv
            assets/benchmark_bar.png
